resource_types:
  - name: mock
    source:
      repository: concourse/mock-resource
      tag: 0.12.4-alpine
resources:
  - name: mock
    type: mock
    source:
      force_version: "true"
      log: ok
