resource_types:
  - name: mock
    source:
      repository: concourse/mock-resource
      tag: 0.13.0
resources:
  - name: mock
    type: mock
    source:
      force_version: "true"
      log: ok
  - name: git
    type: git
    source:
      uri: https://github.com/frantjc/forge
