version: "2"
linters:
  enable:
    - copyloopvar
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - importas
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - testpackage
    - thelper
    - unconvert
    - usetesting
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
