run:
  timeout: 5m
linters:
  enable:
    - dupl
    - exportloopref
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - importas
    - megacheck
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - unconvert
    # test
    - tenv
    - testpackage
    - thelper
    # auto-fix
    - godot
    - gofmt
    - goimports
    - misspell
    - gofumpt
    - whitespace
