run:
  timeout: 5m
linters:
  enable:
    - dupl
    - copyloopvar
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - importas
    - gosimple
    - staticcheck
    - unused
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - unconvert
    # test
    - testpackage
    - thelper
    - usetesting
    # auto-fix
    - godot
    - gofmt
    - goimports
    - misspell
    - gofumpt
    - whitespace
