version: 2
builds:
  - main: ./cmd/forge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
release:
  prerelease: auto
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
brews:
  - repository:
      owner: frantjc
      name: homebrew-tap
    directory: Formula
    skip_upload: auto
    homepage:  https://github.com/frantjc/forge
    description: Easily run reusable steps from proprietary CI systems.
    license: MIT
    test: |
      system "#{bin}/forge --version"
