version: 2
builds:
  - main: ./cmd/forge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
upx:
  - enabled: true
    goos:
      - linux
release:
  prerelease: auto
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
homebrew_casks:
  - repository:
      owner: frantjc
      name: homebrew-tap
    name: forge
    homepage: https://github.com/frantjc/forge
    description: Easily run reusable steps from proprietary CI systems.
    conflicts:
      - formula: forge
    hooks:
      post:
        install: |
          if OS.mac?
            if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
              system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvglsm"]
            end
          end
