builds:
  - main: ./cmd/forge
    ldflags:
      - -s -w -X github.com/frantjc/forge.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
brews:
  - repository:
      owner: frantjc
      name: homebrew-tap
    folder: Formula
    skip_upload: auto
    homepage:  https://github.com/frantjc/forge
    description: Easily run reusable steps from proprietary CI systems.
    license: MIT
    test: |
      system "#{bin}/forge --version"
