repos:
  - repo: https://github.com/frantjc/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: go-fmt
      - id: golangci-lint
      - id: go-build
      - id: go-test
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
