name: Setup Forge
description: |
  Use Forge to easily run reusable steps from other proprietary CI systems.
author: frantjc
branding:
  color: yellow
  icon: box
inputs:
  version:
    description: |
      Version of Forge to install.
runs:
  using: node20
  main: .github/actions/setup-forge/dist/index.js
