name: Setup Forge
description: |
  Use Forge to easily run reusable steps from other proprietary CI systems.
author: frantjc
branding:
  color: yellow
  icon: box
inputs:
  version:
    description: |
      Version of Forge to install.
  install:
    description: |
      Whether or not to install Forge.
    default: true
  get:
    description: |
      Concourse resource to get. Cannot be set at the same time as `put`.
  put:
    description: |
      Concourse resource to put. Cannot be set at the same time as `get`.
  params:
    description: |
      Newline-delimited parameters to use.
  config:
    description: |
      Config file to use.
runs:
  using: node20
  main: .github/action/dist/index.js
