// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"sort"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/frantjc/forge/internal/dagger"
	"github.com/frantjc/forge/internal/querybuilder"
	"github.com/frantjc/forge/internal/telemetry"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject = querybuilder.GraphQLMarshaller

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Forge) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Forge) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func (r PreAction) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Action Action
	}
	concrete.Action = r.Action
	return json.Marshal(&concrete)
}

func (r *PreAction) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Action Action
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Action = concrete.Action
	return nil
}

func (r Resource) MarshalJSON() ([]byte, error) {
	var concrete struct {
		FinalizedResource FinalizedResource
		Source            []string
	}
	concrete.FinalizedResource = r.FinalizedResource
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *Resource) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		FinalizedResource FinalizedResource
		Source            []string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.FinalizedResource = concrete.FinalizedResource
	r.Source = concrete.Source
	return nil
}

func (r Action) MarshalJSON() ([]byte, error) {
	var concrete struct {
		PostAction PostAction
	}
	concrete.PostAction = r.PostAction
	return json.Marshal(&concrete)
}

func (r *Action) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		PostAction PostAction
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.PostAction = concrete.PostAction
	return nil
}

func (r PostAction) MarshalJSON() ([]byte, error) {
	var concrete struct {
		FinalizedAction FinalizedAction
		Ref             *dagger.GitRef
		Metadata        string
		Subpath         string
		Inputs          []string
	}
	concrete.FinalizedAction = r.FinalizedAction
	concrete.Ref = r.Ref
	concrete.Metadata = r.Metadata
	concrete.Subpath = r.Subpath
	concrete.Inputs = r.Inputs
	return json.Marshal(&concrete)
}

func (r *PostAction) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		FinalizedAction FinalizedAction
		Ref             *dagger.GitRef
		Metadata        string
		Subpath         string
		Inputs          []string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.FinalizedAction = concrete.FinalizedAction
	r.Ref = concrete.Ref
	r.Metadata = concrete.Metadata
	r.Subpath = concrete.Subpath
	r.Inputs = concrete.Inputs
	return nil
}

func (r FinalizedAction) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Ctr *dagger.Container
	}
	concrete.Ctr = r.Ctr
	return json.Marshal(&concrete)
}

func (r *FinalizedAction) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Ctr *dagger.Container
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Ctr = concrete.Ctr
	return nil
}

func (r FinalizedResource) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Ctr  *dagger.Container
		Name string
	}
	concrete.Ctr = r.Ctr
	concrete.Name = r.Name
	return json.Marshal(&concrete)
}

func (r *FinalizedResource) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Ctr  *dagger.Container
		Name string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Ctr = concrete.Ctr
	r.Name = concrete.Name
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	var gqlErr *gqlerror.Error
	if errors.As(rerr, &gqlErr) {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		var exec *dagger.ExecError
		if errors.As(err, &exec) {
			return exec.Unwrap()
		}
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Action":
		switch fnName {
		case "Main":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Main(&parent, ctx)
		case "Post":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Post(&parent, ctx)
		case "WithInput":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var value string
			if inputArgs["value"] != nil {
				err = json.Unmarshal([]byte(inputArgs["value"]), &value)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg value", err))
				}
			}
			return (*Action).WithInput(&parent, name, value), nil
		case "WithEnv":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var value string
			if inputArgs["value"] != nil {
				err = json.Unmarshal([]byte(inputArgs["value"]), &value)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg value", err))
				}
			}
			return (*Action).WithEnv(&parent, name, value), nil
		case "WithToken":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var token *dagger.Secret
			if inputArgs["token"] != nil {
				err = json.Unmarshal([]byte(inputArgs["token"]), &token)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg token", err))
				}
			}
			return (*Action).WithToken(&parent, token), nil
		case "WithDebug":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).WithDebug(&parent), nil
		case "WithRef":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ref *dagger.GitRef
			if inputArgs["ref"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ref"]), &ref)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ref", err))
				}
			}
			return (*Action).WithRef(&parent, ref), nil
		case "Container":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Container(&parent), nil
		case "Terminal":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Terminal(&parent), nil
		case "Sync":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Sync(&parent, ctx)
		case "Stdout":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Stdout(&parent, ctx)
		case "Stderr":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Stderr(&parent, ctx)
		case "CombinedOutput":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).CombinedOutput(&parent, ctx)
		case "Workspace":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Workspace(&parent), nil
		case "Toolcache":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Toolcache(&parent), nil
		case "Action":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Action(&parent), nil
		case "Home":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Home(&parent), nil
		case "Env":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Env(&parent, ctx)
		case "State":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).State(&parent, ctx)
		case "Output":
			var parent Action
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Action).Output(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "FinalizedAction":
		switch fnName {
		case "Container":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Container(&parent), nil
		case "Terminal":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Terminal(&parent), nil
		case "Sync":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Sync(&parent, ctx)
		case "Stdout":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Stdout(&parent, ctx)
		case "Stderr":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Stderr(&parent, ctx)
		case "CombinedOutput":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).CombinedOutput(&parent, ctx)
		case "Workspace":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Workspace(&parent), nil
		case "Toolcache":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Toolcache(&parent), nil
		case "Action":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Action(&parent), nil
		case "Home":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Home(&parent), nil
		case "Env":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Env(&parent, ctx)
		case "State":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).State(&parent, ctx)
		case "Output":
			var parent FinalizedAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedAction).Output(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "FinalizedResource":
		switch fnName {
		case "Container":
			var parent FinalizedResource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedResource).Container(&parent), nil
		case "Sync":
			var parent FinalizedResource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedResource).Sync(&parent, ctx)
		case "Stdout":
			var parent FinalizedResource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedResource).Stdout(&parent, ctx)
		case "Stderr":
			var parent FinalizedResource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedResource).Stderr(&parent, ctx)
		case "CombinedOutput":
			var parent FinalizedResource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedResource).CombinedOutput(&parent, ctx)
		case "Terminal":
			var parent FinalizedResource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedResource).Terminal(&parent), nil
		case "Workdir":
			var parent FinalizedResource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FinalizedResource).Workdir(&parent), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Forge":
		switch fnName {
		case "Use":
			var parent Forge
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var action string
			if inputArgs["action"] != nil {
				err = json.Unmarshal([]byte(inputArgs["action"]), &action)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg action", err))
				}
			}
			var workspace *dagger.Directory
			if inputArgs["workspace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspace"]), &workspace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspace", err))
				}
			}
			return (*Forge).Use(&parent, ctx, action, workspace)
		case "Resource":
			var parent Forge
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var resource string
			if inputArgs["resource"] != nil {
				err = json.Unmarshal([]byte(inputArgs["resource"]), &resource)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg resource", err))
				}
			}
			var pipeline *dagger.File
			if inputArgs["pipeline"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pipeline"]), &pipeline)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pipeline", err))
				}
			}
			var workdir *dagger.Directory
			if inputArgs["workdir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workdir"]), &workdir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workdir", err))
				}
			}
			return (*Forge).Resource(&parent, ctx, resource, pipeline, workdir)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "PostAction":
		switch fnName {
		case "Post":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Post(&parent, ctx)
		case "WithInput":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var value string
			if inputArgs["value"] != nil {
				err = json.Unmarshal([]byte(inputArgs["value"]), &value)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg value", err))
				}
			}
			return (*PostAction).WithInput(&parent, name, value), nil
		case "WithEnv":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var value string
			if inputArgs["value"] != nil {
				err = json.Unmarshal([]byte(inputArgs["value"]), &value)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg value", err))
				}
			}
			return (*PostAction).WithEnv(&parent, name, value), nil
		case "WithToken":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var token *dagger.Secret
			if inputArgs["token"] != nil {
				err = json.Unmarshal([]byte(inputArgs["token"]), &token)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg token", err))
				}
			}
			return (*PostAction).WithToken(&parent, token), nil
		case "WithDebug":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).WithDebug(&parent), nil
		case "WithRef":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ref *dagger.GitRef
			if inputArgs["ref"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ref"]), &ref)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ref", err))
				}
			}
			return (*PostAction).WithRef(&parent, ref), nil
		case "Container":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Container(&parent), nil
		case "Terminal":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Terminal(&parent), nil
		case "Sync":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Sync(&parent, ctx)
		case "Stdout":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Stdout(&parent, ctx)
		case "Stderr":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Stderr(&parent, ctx)
		case "CombinedOutput":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).CombinedOutput(&parent, ctx)
		case "Workspace":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Workspace(&parent), nil
		case "Toolcache":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Toolcache(&parent), nil
		case "Action":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Action(&parent), nil
		case "Home":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Home(&parent), nil
		case "Env":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Env(&parent, ctx)
		case "State":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).State(&parent, ctx)
		case "Output":
			var parent PostAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PostAction).Output(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "PreAction":
		switch fnName {
		case "Pre":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Pre(&parent, ctx)
		case "Main":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Main(&parent, ctx)
		case "Post":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Post(&parent, ctx)
		case "WithInput":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var value string
			if inputArgs["value"] != nil {
				err = json.Unmarshal([]byte(inputArgs["value"]), &value)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg value", err))
				}
			}
			return (*PreAction).WithInput(&parent, name, value), nil
		case "WithEnv":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var value string
			if inputArgs["value"] != nil {
				err = json.Unmarshal([]byte(inputArgs["value"]), &value)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg value", err))
				}
			}
			return (*PreAction).WithEnv(&parent, name, value), nil
		case "WithToken":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var token *dagger.Secret
			if inputArgs["token"] != nil {
				err = json.Unmarshal([]byte(inputArgs["token"]), &token)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg token", err))
				}
			}
			return (*PreAction).WithToken(&parent, token), nil
		case "WithDebug":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).WithDebug(&parent), nil
		case "WithRef":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ref *dagger.GitRef
			if inputArgs["ref"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ref"]), &ref)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ref", err))
				}
			}
			return (*PreAction).WithRef(&parent, ref), nil
		case "Container":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Container(&parent), nil
		case "Terminal":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Terminal(&parent), nil
		case "Sync":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Sync(&parent, ctx)
		case "Stdout":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Stdout(&parent, ctx)
		case "Stderr":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Stderr(&parent, ctx)
		case "CombinedOutput":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).CombinedOutput(&parent, ctx)
		case "Workspace":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Workspace(&parent), nil
		case "Toolcache":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Toolcache(&parent), nil
		case "Home":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Home(&parent), nil
		case "Env":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Env(&parent, ctx)
		case "State":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).State(&parent, ctx)
		case "Output":
			var parent PreAction
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PreAction).Output(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Resource":
		switch fnName {
		case "Get":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var version []string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			var param []string
			if inputArgs["param"] != nil {
				err = json.Unmarshal([]byte(inputArgs["param"]), &param)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg param", err))
				}
			}
			return (*Resource).Get(&parent, version, param)
		case "Check":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var version []string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			return (*Resource).Check(&parent, version)
		case "Put":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var param []string
			if inputArgs["param"] != nil {
				err = json.Unmarshal([]byte(inputArgs["param"]), &param)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg param", err))
				}
			}
			return (*Resource).Put(&parent, param)
		case "Container":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Resource).Container(&parent), nil
		case "Sync":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Resource).Sync(&parent, ctx)
		case "Stdout":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Resource).Stdout(&parent, ctx)
		case "Stderr":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Resource).Stderr(&parent, ctx)
		case "CombinedOutput":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Resource).CombinedOutput(&parent, ctx)
		case "Terminal":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Resource).Terminal(&parent), nil
		case "Workdir":
			var parent Resource
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Resource).Workdir(&parent), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
