package forge

// format .proto before generating from it
// then generate .go from .proto
//go:generate make proto

// format .go, including .go generated by .proto
// were it to not meet gofmt's standards
//go:generate make fmt

//go:generate make lint

// build the shim binary which is often copied into containers
// and used as their entrypoint, then pack the shim binary
// so that copy times are as fast as possible
//go:generate make shim
