// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: metal.proto

package forge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitCode int64 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
}

func (x *Metal) Reset() {
	*x = Metal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metal) ProtoMessage() {}

func (x *Metal) ProtoReflect() protoreflect.Message {
	mi := &file_metal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metal.ProtoReflect.Descriptor instead.
func (*Metal) Descriptor() ([]byte, []int) {
	return file_metal_proto_rawDescGZIP(), []int{0}
}

func (x *Metal) GetExitCode() int64 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_metal_proto protoreflect.FileDescriptor

var file_metal_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66,
	0x6f, 0x72, 0x67, 0x65, 0x22, 0x24, 0x0a, 0x05, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x12, 0x1b, 0x0a,
	0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x72, 0x61, 0x6e, 0x74, 0x6a, 0x63,
	0x2f, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metal_proto_rawDescOnce sync.Once
	file_metal_proto_rawDescData = file_metal_proto_rawDesc
)

func file_metal_proto_rawDescGZIP() []byte {
	file_metal_proto_rawDescOnce.Do(func() {
		file_metal_proto_rawDescData = protoimpl.X.CompressGZIP(file_metal_proto_rawDescData)
	})
	return file_metal_proto_rawDescData
}

var file_metal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metal_proto_goTypes = []interface{}{
	(*Metal)(nil), // 0: forge.Metal
}
var file_metal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metal_proto_init() }
func file_metal_proto_init() {
	if File_metal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metal_proto_goTypes,
		DependencyIndexes: file_metal_proto_depIdxs,
		MessageInfos:      file_metal_proto_msgTypes,
	}.Build()
	File_metal_proto = out.File
	file_metal_proto_rawDesc = nil
	file_metal_proto_goTypes = nil
	file_metal_proto_depIdxs = nil
}
