// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: pkg/forgeconcourse/config.proto

package forgeconcourse

import (
	"github.com/frantjc/forge/pkg/concourse"
)

type Config struct {
	ResourceTypes []*concourse.ResourceType `yaml:"resource_types,omitempty"`
	Resources     []*concourse.Resource     `yaml:"resources,omitempty"`
}

func (c *Config) GetResourceTypes() []*concourse.ResourceType {
	return c.ResourceTypes
}

func (c *Config) GetResources() []*concourse.Resource {
	return c.Resources
}
