name: Build Action
on:
  push:
    branches:
      - main
    paths:
      - .github/action/**
      - .github/workflows/build-action.yml
    paths-ignore:
      - .github/action/dist/**
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: .github/action/yarn.lock
      - name: Run make action
        run: |
          cd .github/action
          yarn
          cd ../..
          make action
      - uses: peter-evans/create-pull-request@v6
        env:
          COMMIT_MESSAGE: |
            Update .github/action built by GitHub Actions Workflow "${{ github.workflow }}" run ${{ github.server_url }}/${{ github.repository }}/actions/${{ github.run_id }} for user ${{ github.actor }} from commit ${{ github.sha }}.
        with:
          add-paths: |
            .github/action
          reviewers: |
            ${{ github.actor }}
          title: |
            Build .github/action
          commit-message: ${{ env.COMMIT_MESSAGE }}
          body: ${{ env.COMMIT_MESSAGE }}
          branch: github-actions/gen/github/action
          delete-branch: true
          labels: github_actions
