name: CI
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          install_args: dagger
      # FIXME(frantjc): Docker tests still fail in Dagger.
      # - name: Prepare .env
      #   run: |
      #     cat <<EOF > .env
      #     forgeDev_test_docker=$(which docker)
      #     forgeDev_test_dockerSock=$(docker context inspect --format '{{.Endpoints.docker.Host}}' | sed 's|unix://||')
      #     EOF
      - run: dagger check
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          install_args: go
      - name: Prepare shim
        env:
          CGO_ENABLED: "0"
        run: |
          rm internal/bin/shim
          go build -o internal/bin/shim ./internal/cmd/shim
      - name: Run go test
        run: go test -race -tags docker,dockerd,shim ./...
