name: Runs Using Nonstandard Dockerfile
on: workflow_dispatch
permissions:
  contents: read
jobs:
  uses-nonstd-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: frantjc/forge/testdata/actions/dockerfile/nonstd@main
