name: Save State
on: workflow_dispatch
permissions:
  contents: read
jobs:
  save-state:
    runs-on: ubuntu-latest
    steps:
      - uses: frantjc/forge/testdata/actions/save-state@${{ github.sha }}
